#!/bin/sh

# SETTINGS FILE FOR CONFIGCLOUD INSTALLER - defines items to ignore, link, copy, and create
#
#     This script is a component of ConfigCloud
#       https://github.com/robertpeteuil/configcloud
#
#     Robert Peteuil (c) 2018
#
#   There are four actions: ignore, link_children, copy, link
#     Each action has a corresponding variable that list files and dirs (with wildcards)
#     The items in each variable are space separated
#
#   The actions are prioritized:
#     IGNORE overrides LINK_CHILDREN
#     LINK_CHILDREN overrides COPY
#     COPY overrides LINK


# IGNORE THESE FILES (DO NOT COPY OR LINK THEM)
#   The following wiles are ignored by default:
#     Installer, this settings file, info-files,
#     Icon file(s), .md & .txt files, and LICENSE
ignore='zref* install* Icon* *.md *.txt LICENSE'

# LINK CONTENTS OF DIR - CREATE DIR IF NECESSARY
#   Will NOT delete an existing directory, but will place links in it
#   Replacing a directory requires manual deletion before running the Installer
link_children=''

# COPY THESE FILES
copy=''

# SYM-LINK THESE FILES
link='*'
