#!/bin/sh

# SETTINGS FILE FOR INSTALL.SH
#
# This file tells install.sh what to ignore, link, copy, and create
#
# There are four possible actions: ignore, link_children, copy, link
#
# Each action has a corresponding string
#   These strings list files & globs for the action to be performed
#     The items in each string are space separated
#
# The actions are prioritized in the listed order, and as follows:
#   IGNORE overrides LINK_CHILDREN
#   LINK_CHILDREN overrides COPY
#   COPY overrides LINK

# IGNORE THESE FILES (DO NOT COPY OR LINK THEM TO USER'S HOME-dir)
#   This default settings file ignores these items:
#     Installer-related files: scripts directory, this settings file
#     Other info-files: Icon file(s), .sh scripts, .md & .txt files
ignore='zref* install* Icon* *.md *.txt LICENSE'

# LINK DIR CONTENTS - MAKE DIR IF NECESSARY
#   Will NOT delete n existing directory, but will still place links in it
#   To replace a directory, manually delete it before running this script
link_children=''

# COPY THESE FILES
copy=''

# SYM-LINK THESE FILES
link='*'
